name: Build binary for Windows
on:
  push:
    tags:
      - v*.*.*
jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            src-tauri/target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
      - uses: actions/setup-node@v1
        with:
          node-version: 16
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - run: yarn --frozen-lockfile
      - run: yarn tauri build
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          prerelease: true
          files: src-tauri/target/release/osc-ws.exe
  debug-build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            src-tauri/target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
      - uses: actions/setup-node@v1
        with:
          node-version: 16
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - run: yarn --frozen-lockfile
      - run: yarn tauri build --debug
      - run: mv src-tauri/target/debug/osc-ws.exe src-tauri/target/debug/osc-ws.debug.exe
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          prerelease: true
          files: src-tauri/target/debug/osc-ws.debug.exe
